name: Release epub

on:
  schedule: 
    - cron: "0 2 * * *"
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Papeer
      run: go install github.com/lapwat/papeer@latest

    - name: Generate Rust Epub
      run: | 
       export RELEASE_TAG=$(date +"%Y%m%d")
       echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
       papeer get --selector='ol>li>a' --output The_Rust_Programming_Language_$RELEASE_TAG.epub --format=epub https://doc.rust-lang.org/book/
       ls ./
       
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: The Rust Book EPUB - ${{ env.RELEASE_TAG }}
        tag_name: v${{ env.RELEASE_TAG }}
        body: Release v${{ env.RELEASE_TAG }}
        files: The_Rust_Programming_Language_${{ env.RELEASE_TAG }}.epub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: starmun-0010/therustbook
    
